name: Development Build (Galaxy A50)

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'wip-*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Build KSU'
        required: false

jobs:
  oneui-4-p:
    name: Build One UI 4 (Permissive)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Manila"
        timezoneMacos: "Asia/Manila"
        timezoneWindows: "Philippine Standard Time"

    - name: Export build branch
      id: branch_name
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

    - name: Update Debian/Ubuntu Repositories
      run: sudo apt-get update

    - name: Install Dependencies
      run: sudo apt-get install -y bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 jq

    - name: Build Mint Kernel (Permissive)
      run: |
        set -eo pipefail
        echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
        ./build.sh --magisk --automated --device a50 --variant oneui --android 12 --permissive

    - name: Prepare Release Package
      run: |
        mkdir -p ./release
        mv -f $(find ./ -iname MintBeta-*.zip) ./release/

    - name: Save Kernel Config
      run: cp .config ./release/kernel_config_a50_oneui-4-p.txt

    - name: Upload Kernel Image
      uses: actions/upload-artifact@v3
      with:
        name: One UI 4 Kernel Image (Permissive)
        path: 'tools/make/boot.img'

    - name: Upload Kernel Configs
      uses: actions/upload-artifact@v3
      with:
        name: Kernel Configs
        path: './release/kernel_config_a50_oneui-4-p.txt'

    - name: Upload Release Package
      uses: actions/upload-artifact@v3
      with:
        name: Release
        path: './release'
