name: Upstream Kernel to 4.19

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'wip-*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Target kernel version'
        default: '4.19'
        required: true

jobs:
  upstream-kernel:
    name: Upstream Kernel to 4.19
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Create new branch
      run: |
        git checkout -b upstream-4.19-${{ github.run_number }}
        git push -u origin upstream-4.19-${{ github.run_number }}

    - name: Fetch Linux 4.19 kernel
      run: |
        git remote add upstream https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
        git fetch upstream v4.19

    - name: Cherry-pick compatible changes
      run: |
        git cherry-pick -n upstream/v4.19
        git status
        git diff --name-only --diff-filter=U | xargs git checkout --theirs
        git add .
        git commit -m "Upstream to Linux 4.19 with compatible changes"

    - name: Push changes
      run: |
        git push origin upstream-4.19-${{ github.run_number }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        title: "Upstream to Linux 4.19"
        body: "This PR upstreams the kernel to version 4.19 with compatible changes."
        branch: upstream-4.19-${{ github.run_number }}
        base: ${{ github.ref }}
