name: Development Build (Galaxy A50)

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'wip-*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Build KSU'
        required: false

jobs:
  oneui-4-p:
    name: Build One UI 4 (Permissive)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Manila"
        timezoneMacos: "Asia/Manila"
        timezoneWindows: "Philippine Standard Time"

    - name: Export build branch
      id: branch_name
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

    - name: Update Debian/Ubuntu Repositories
      run: sudo apt-get update

    - name: Install Dependencies
      run: sudo apt-get install -y bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 jq

    - name: Upstream Kernel to 4.19
      run: |
        git fetch --all --tags
        git checkout -b upstream-4.19 v4.19
        git am patches/*.patch || true

    - name: Update Kernel Configuration
      run: |
        make ARCH=arm64 exynos9610-a50_core_defconfig
        ./scripts/kconfig/merge_config.sh -m -r \
          arch/arm64/configs/exynos9610-a50_core_defconfig \
          kernel/configs/mint_variant_oneui.config \
          kernel/configs/mint_partial-deknox-12.config \
          kernel/configs/mint_mali-12.config

    - name: Enable Additional Features
      run: |
        echo "CONFIG_LTO=y" >> arch/arm64/configs/tmp_exynos9610-a50_oneui_defconfig
        echo "CONFIG_LTO_CLANG=y" >> arch/arm64/configs/tmp_exynos9610-a50_oneui_defconfig
        echo "CONFIG_DYNAMIC_STUNE_BOOST=y" >> arch/arm64/configs/tmp_exynos9610-a50_oneui_defconfig
        echo "CONFIG_ENERGY_MODEL=y" >> arch/arm64/configs/tmp_exynos9610-a50_oneui_defconfig
        echo "CONFIG_CPU_FREQ_GOV_SCHEDUTIL=y" >> arch/arm64/configs/tmp_exynos9610-a50_oneui_defconfig

    - name: Build Mint Kernel (Permissive)
      run: |
        set -eo pipefail
        echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
        ./build.sh --magisk --automated --device a50 --variant oneui --android 12 --permissive

    - name: Prepare Release Package
      run: |
        mkdir -p ./release
        mv -f $(find ./ -iname MintBeta-*.zip) ./release/

    - name: Save Kernel Config
      run: cp .config ./release/kernel_config_a50_oneui-4-p.txt

    - name: Upload Kernel Image
      uses: actions/upload-artifact@v3
      with:
        name: One UI 4 Kernel Image (Permissive)
        path: 'tools/make/boot.img'

    - name: Upload Kernel Configs
      uses: actions/upload-artifact@v3
      with:
        name: Kernel Configs
        path: './release/kernel_config_a50_oneui-4-p.txt'

    - name: Upload Release Package
      uses: actions/upload-artifact@v3
      with:
        name: Release
        path: './release'
