name: Optimize Kernel Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  optimize_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install Terser
        run: npm install -g terser@latest

      # Step to enforce a timeout of exactly 3 minutes
      - name: Recode and Optimize Files
        run: |
          timeout 180s find . -type d \( -name 'kernel' -o -name 'arch' \) -exec sed -i 's/kernel/melernel/g' {}/* \; && timeout 180s find . -type f \( -name '*.c' -o -name '*.h' -o -name 'Makefile*' \) -exec terser --compress --mangle --output {} {} \;
        continue-on-error: true

      - name: Mark step as successful (if exceeds 3 minutes)
        if: always()
        run: exit 0

      - name: Zip Optimized Files
        run: zip -r optimized_files.zip * --exclude=".git*"

      - name: Upload Zip File
        uses: actions/upload-artifact@v2
        with:
          name: optimized-files
          path: optimized_files.zip
