name: Stable Release Build (Galaxy A50)

on:
  push:
    branches:
      - 'android-*'
  workflow_dispatch:  # Add workflow_dispatch trigger

jobs:
  oneui-s-m:
    name: Build One UI 4 (Magisk)
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      
    steps:
      - uses: actions/checkout@v2

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Manila"
          timezoneMacos: "Asia/Manila"
          timezoneWindows: "Philippine Standard Time"

      - name: Export build branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: branch_name

      - name: Update Debian/Ubuntu Repositories
        run: sudo apt-get update

      - name: Install Debian/Ubuntu dependencies
        run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 jq -y

      - name: Build Mint kernel
        run: |
            set -eo pipefail
            chmod 755 scripts/*
            chmod 755 build.sh
            find . -type f -exec chmod 755 {} +
            echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
            ./build.sh --magisk --automated --device a50 --variant oneui --android 12 --permissive

      - name: Prepare release package
        run: |
            mkdir -p ./release
            mv -f $(find ./ -iname "Mint*-*.zip") ./release/

      - name: Prepare build config artifact
        run: |
            cp .config ./release/kernel_config_a50_oneui-s-p.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Release
          path: |
            release/
            tools/make/boot.img
            release/kernel_config_a50_oneui-s-p.txt
          if-no-files-found: error
          
